### ISSUE TITLE
More endpoints

### ISSUE THREAD

**Issue by antonkandersson** [benhowdle89/reqres#10]
Hi, 
I've been using reqres for mockuping, but we have a need for mocked endpoints such as `/orders` and `/articles`. Is reqres only supposed to support user, or could/should I make a pull request adding these?

**Comment by benhowdle89** [comment]
From the docs:

> Any endpoint that contains "<resource>" can be substituted with anything you supply, ie. "products", "accounts", etc..the API will just respond with various Pantone colours (defined in data.json under the "unknown" key)

So if you, at the moment, send a request to `/orders`, it will respond with Pantone sample data. However, if you wish for the service to respond with more semantic data, ie. related to "orders" or "articles", then yes, submit a Pull Request and modify this config JSON file: https://github.com/benhowdle89/reqres/blob/master/data.json you'll see "users" and "unknown" - unknown is used for any request *apart from* `/users`. So adding your own key in this object will send back the data you stipulate in this file.

**Comment by antonkandersson** [comment]
Oh thanks, totally missed that. My bad. Thanks for quick response.
