### ISSUE TITLE
[Request] Adding support for HTTPS on hosted server

### ISSUE THREAD

**Issue by ScheerMT** [benhowdle89/reqres#11]
The addition of responding to HTTPS would increase the usefulness of this service :)

It looks like free SSL certificate providers do exist and is actually something coming into vogue now..

**Comment by jeffbski** [comment]
Yes, I totally agree. Since many examples are served over https, the browser restricts doing non-https xhr requests. Please add SSL. You can use lets-encrypt to get free certificates.

**Comment by Atinux** [comment]
👍 

It can be made easily by using CloudFare and it's free @benhowdle89

**Comment by benhowdle89** [comment]
Done https://reqres.in/ 👍

**Comment by Atinux** [comment]
You rock @benhowdle89
