### ISSUE TITLE
Random delayed response?

### ISSUE THREAD

**Issue by jlem** [benhowdle89/reqres#14]
Just for convenience, it would be good if you could do something like `?delay=random` with some sane defaults (200ms to 3000ms). Would save anyone doing testing from having to define the randomizer for the delay (not that it's hard, it's just extra noise when trying to show a quick demonstration of something)

**Comment by benhowdle89** [comment]
Done. https://reqres.in/api/users?delay=random should do exactly what you stipulated 👍
