### ISSUE TITLE
CORS: Not accessible from CodePen

### ISSUE THREAD

**Issue by sevilayha** [benhowdle89/reqres#15]
Hey, I've been using reqres for a lot of my demos. Great stuff.

Has something changed recently? I'm getting a redirect because of a CORS problem.

Here's a CodePen that displays the problem: http://codepen.io/sevilayha/pen/wgBOop/?editors=0010

1. Simple AJAX call to `http://reqres.in/api/users` to `GET` users
2. Open up console
3. Error is: 

```
XMLHttpRequest cannot load http://reqres.in/api/users. Redirect from 'http://reqres.in/api/users' to 'https://reqres.in/api/users' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.
```

Thanks.

**Comment by benhowdle89** [comment]
Something has, and it's my bad. It's now accessible via `https`, so just switch your URLs to that and you're all good 👍

**Comment by sevilayha** [comment]
Thanks for the fast update. Much appreciated!

**Comment by kaleoshell** [comment]
Thanks!! me breaking my head here and this was the problem of https

**Comment by benhowdle89** [comment]
@kaleoshell don't break your head friend.
