### ISSUE TITLE
Get Users with query string instead of routing parameter

### ISSUE THREAD

**Issue by pottabathini** [benhowdle89/reqres#17]
As per the docs to get user by id need to send request like
`GET https://reqres.in/api/users/2` it will return JSON response of the user.
Is there any alternative way like sending userid in query string example:
`GET https://reqres.in/api/users?id=2`

we tried with id as query string it is returning pagination of all the users :-(

**Comment by benhowdle89** [comment]
Done!

**Comment by sevillaarvin** [comment]
I tested this and I see that it works, but it's not documented in the front page https://reqres.in/
