### ISSUE TITLE
Stop retaining POSTed data

### ISSUE THREAD

**Issue by davidbanham** [benhowdle89/reqres#20]
You explicitly say that you don't retain any data sent to the service:

https://github.com/benhowdle89/reqres/blob/master/views/index.html#L149

Yet you log all POSTed data to stdout.

https://github.com/benhowdle89/reqres/blob/master/routes/index.js#L28

And from there who knows where it goes? That's a pretty egregious oversight given all the reassuring noises you make on the marketing site.

**Comment by benhowdle89** [comment]
Dang, massive oversight on my part, big apologies.

Thanks for bringing it to my attention in such a diplomatic way 👍
