### ISSUE TITLE
adding parameter

### ISSUE THREAD

**Issue by navotera** [benhowdle89/reqres#22]
can this make work  ?
https://reqres.in/api/users?page=2?per_page=10

**Comment by benhowdle89** [comment]
I can, but the format will be `https://reqres.in/api/users?page=2&per_page=10`, you had a `?` in there, and it needs to be a `&`. I'll complete this when I can.

**Comment by benhowdle89** [comment]
Done https://reqres.in/api/users?per_page=10 👍

**Comment by navotera** [comment]
thanks u sir its great
