### ISSUE TITLE
After running in local what is next

### ISSUE THREAD

**Issue by johndavemanuel** [benhowdle89/reqres#38]
I follow the instructions and I ended here

![image](https://user-images.githubusercontent.com/8970365/51221554-ed523800-1974-11e9-8e2a-0f24ec5404b4.png)

What is the next step after this?

**Comment by edwardfhsiao** [comment]
maybe try ```http://0.0.0.0:5000/api/users?page=2``` ?

**Comment by johndavemanuel** [comment]
Hi!

This site can’t be reached The webpage at http://0.0.0.0:5000/api/users?page=2 might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

**Comment by edwardfhsiao** [comment]
I have no idea then. I just git cloned it and run successfully. Maybe it related to your windows system or network configuration or even VPN.

**Comment by johndavemanuel** [comment]
I guess. BTW, thanks for your answer!

**Comment by johndavemanuel** [comment]
@edwardfhsiao do you have idea how can I run the documentation inside public?

**Comment by fier4jat** [comment]
http://localhost:5000/api...

**Comment by johndavemanuel** [comment]
I already made it running

Thanks everyone
