### ISSUE TITLE
Responses for POST-CREATE, PUT-UPDATE and PATCH-UPDATE return an incomplete data 

### ISSUE THREAD

**Issue by Biloleg** [benhowdle89/reqres#42]
When I send  POST-CREATE, PUT-UPDATE or PATCH-UPDATE request I expect to get in response name, job and creation time like in response window on site:
{
    "name": "morpheus",
    "job": "zion resident",
    "updatedAt": "2019-05-08T13:32:53.794Z"
}

But in real (Postman or Java HTTPClient) I get updatedAt only:

{
    "updatedAt": "2019-05-08T13:32:53.794Z"
}

**Comment by benhowdle89** [comment]
Trying to reproduce your error but struggling to.

If I send this:

```
curl -X POST \
  https://reqres.in/api/users \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "foobar"
}'
```

I get the response:

```
{
    "name": "foobar",
    "id": "638",
    "createdAt": "2019-05-13T10:57:18.211Z"
}
```

**Comment by Biloleg** [comment]
Yes )))

I just miss header 'Content-Type: application/json'

With it everything work fine

Thanks

**Comment by Biloleg** [comment]
Everything work fine with header Content-Type: application/json
