### ISSUE TITLE
Example list items in "Give it a try" should be links

### ISSUE THREAD

**Issue by mk-pmb** [benhowdle89/reqres#47]
… so we can easily copy the link URL, open it in a new tab, and even try it w/o JavaScript enabled. In browsers that support and allow JS, you can just `preventDefault()` to keep the old effect. Same for the URL shown in the "Request" box above.

**Comment by nandhae** [comment]
Can i pick this up if no one else is working on it.

**Comment by mk-pmb** [comment]
As this should be a quick fix, I'd guess it's safe if within 4 to 8 hours no-one says they're on it already.

**Comment by nandhae** [comment]
Cool, Sure. I'm on it.

**Comment by nandhae** [comment]
@mk-pmb Raised a PR. Please do check it out and comment. :)
